// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
     switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-dxGHg2NwFNBV0JP0es-pl0EnlqMIMo',
    appId: '1:51597187129:web:13da892e9afe60e51695e8',
    messagingSenderId: '51597187129',
    projectId: 'reliability-predictor',
    authDomain: 'reliability-predictor.firebaseapp.com',
    storageBucket: 'reliability-predictor.appspot.com',
    measurementId: 'G-YTSCZ98LYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa65K0EL55zD1gA4g0i2lyvXe8XGgVRYA',
    appId: '1:51597187129:android:1512cf061b9abb091695e8',
    messagingSenderId: '51597187129',
    projectId: 'reliability-predictor',
    storageBucket: 'reliability-predictor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhW-i15Q49dlxi0xS_ApSj8Lu6v60hhc',
    appId: '1:51597187129:ios:8b414d18578c15c01695e8',
    messagingSenderId: '51597187129',
    projectId: 'reliability-predictor',
    storageBucket: 'reliability-predictor.appspot.com',
    iosClientId: '51597187129-6jq3shguf4l8lobb23opi69vdc5ite1b.apps.googleusercontent.com',
    iosBundleId: 'com.reliability.app',
  );
}
